POST http://localhost:8080/siloapi/api/medicao/v1/cadastra
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLWFwaSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzE5MDc1ODc0LCJyb2xlIjoiQURNSU4ifQ.SJFNrz-MSEyYXHD6bOy44Mvf8BrJ5e7v4E-70NQuzQY
{
    "applicationID": "1",
    "applicationName": "Teste",
    "devEUI": "1",
    "deviceName": "Teste2",
    "timestamp": 1718982824,
    "fCnt": 2,
    "fPort": 2,
    "data": "010201A3027327CE0368630467011305650000",
    "data_encode": "hexstring",
    "object": {
        "analogInput": 4.19,
        "barometer": 1019,
        "humidity": 49.5,
        "temperature": 27.5,
        "illuminance": 30000
    },
    "adr": false,
    "rxInfo": [
        {
            "gatewayID": "ac1f09fffe0920a2",
            "loRaSNR": 13.8,
            "rssi": -36,
            "location": {
                "latitude": 0,
                "longitude": 0,
                "altitude": 0
            }
        }
    ],
    "txInfo": {
        "frequency": 904500000,
        "dr": 3
    }
}